version: '3.4'

services:
  web:
    container_name: flutter
    image: flutter:latest
    network_mode: "host"
    volumes:
      - /var/data/TheGourmet/deployment/App/default.conf:/etc/nginx/conf.d/default.conf
    - /etc/letsencrypt/live/gourmetapp.net/cert.pem:/etc/nginx/certs/cr.crt
    - /etc/letsencrypt/live/gourmetapp.net/privkey.pem:/etc/nginx/certs/cr.key
    - /var/data/TheGourmet/logs:/var/log/nginx
    ports:
    - "80:80"
    - "443:443"
  operator:
    container_name: meals_operator
    image: meal_opr:latest
    network_mode: "host"
    volumes:
    - /home/azureuser/data:/code/data
    expose:
      - 5000
    ports:
      - "5000:5000"
  inference:
    container_name: inference_server
    image: inf_server:latest
    network_mode: "host"
    volumes:
      - /home/azureuser/model.h5:/code/model.h5
    expose:
      - 5100
    ports:
      - "5100:5100"
