version: '3.4'

services:
  web:
    image: nginx:latest
    container_name: gourmet-react
    volumes:
    #- ./build:/usr/share/nginx/html
    - ./build:/etc/nginx/html
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    depends_on:
      - gateway
      - backend
  gateway:
    build: Gateway
    container_name: gourmet-gateway
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "3001:3001"
    expose:
      - 3001
    #environment:
    #- meals_url=http://meals
    #- gateway_url=gateway
  backend:
    container_name: gourmet-meals
    build: Backend
    restart: on-failure
    ports:
      - "8081:8081"
    expose:
      - 8081
    #environment:
    #  - meals_url=http://meals/api


