version: '3.4'

services:
  web:
    image: nginx:latest
    container_name: gourmet-react
    volumes:
    - ./build:/usr/share/nginx/html
    ports:
      - "0.0.0.0:80:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    depends_on:
      - gateway
      - backend
  gateway:
    build: Gateway
    container_name: gourmet-gateway
    restart: on-failure
    depends_on:
      - backend
    environment:
    - meals_url=http://meals
    - gateway_url=gateway
  backend:
    container_name: gourmet-meals
    build: Backend
    restart: on-failure
    environment:
      - meals_url=http://meals/api


