version: '3.4'

services:
  web:
    image: nginx:latest
    restart: always
    volumes:
      - ./build:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d/
      - ./conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/gourmet.hopto.org/cert.pem:/etc/nginx/certs/cr.crt
      - /etc/letsencrypt/live/gourmet.hopto.org/privkey.pem:/etc/nginx/certs/cr.key
    ports:
      - 80:80
      - 443:443