version: '3.4'

services:
  web:
    container_name: gourmet-flutter
    build: /var/data/TheGourmet/FlutterApp
    volumes:
    - ./conf.d:/etc/nginx/conf.d/
    - /etc/letsencrypt/live/gourmetapp.net/cert.pem:/etc/nginx/certs/cr.crt
    - /etc/letsencrypt/live/gourmetapp.net/privkey.pem:/etc/nginx/certs/cr.key
    ports:
    - "80:80"
    - "443:443"
    depends_on:
      - flask
  flask:
    container_name: gourmet-meals
    build: /var/data/TheGourmet/Flask
    volumes:
    - /home/azureuser/data:/code/data
    - /etc/letsencrypt/live/gourmetapp.net/cert.pem:/code/cert.pem
    - /etc/letsencrypt/live/gourmetapp.net/privkey.pem:/code/privkey.pem   
    expose:
      - 5000
    ports:
      - "5000:5000"


