wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1648394373
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      4: 3.9.6
      5: 0.12.11
      8:
      - 3
      - 5
