version: '3.4'

services:
  web:
    image: nginx:latest
    container_name: gourmet-react
    volumes:
    - ./build:/usr/share/nginx/html
    ports:
    - "3000:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
  backend:
    container_name: gourmet-meals
    build: api
    restart: on-failure
    ports:
      - "5000:5000"
    expose:
      - 5000
    #environment:
    #  - meals_url=http://meals/api


